apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.backend.namespace }}
type: Opaque
data:
  MONGODB_PASSWORD: {{ .Values.backend.secrets.MONGODB_PASSWORD }}