apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-configmap
  namespace: {{ .Values.frontend.namespace }}
  labels:
{{- toYaml .Values.frontend.labels | nindent 4 }}
data:
{{- range $k, $v := .Values.frontend.configmap }}
  {{ $k }}: {{ $v | quote }}
{{- end }}