apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.servicename }}
  namespace: {{ .Values.frontend.namespace }}
  labels:
{{- toYaml .Values.frontend.labels | nindent 4 }}
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.frontend.containerPorts.http }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    id: {{.Values.frontend.labels.id }}