apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx_proxy.name }}
  namespace: {{ .Values.nginx_proxy.namespace }}
  labels:
{{- toYaml .Values.nginx_proxy.labels | nindent 4 }}
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.nginx_proxy.containerPorts.http }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: NodePort
  selector:
    id: {{.Values.nginx_proxy.labels.id }}       # Pod label that service is using to select Pods